#!/bin/sh

set -e

USER="azkaban"
GROUP="azkaban"
PERMISSIONS="0755"
SERVER_DIR="/opt/azkaban-solo"
DATA_DIR="/srv/data/azkaban-solo"
LOG_DIR="/var/log/azkaban-solo"


case "${1}" in
  configure)
    if ! getent group "${GROUP}" &> /dev/null ; then
      addgroup --system "${GROUP}" --quiet
    fi

    if ! id "${USER}" &> /dev/null ; then
      adduser --system --home "${SERVER_DIR}" --no-create-home \
        --ingroup "${GROUP}" --disabled-password \
        --shell /bin/bash "${USER}"
    fi

    install -d -o "${USER}" -g "${GROUP}" -m "${PERMISSIONS}" "${DATA_DIR}"
    install -d -o "${USER}" -g "${GROUP}" -m "${PERMISSIONS}" "${LOG_DIR}"

    chown -R "${USER}":"${GROUP}" "${SERVER_DIR}"
    ;;
esac

