#!/bin/sh

set -e

case "$1" in
  configure)
    user="azkaban"
    group="azkaban"
    serverdir="/opt/azkaban-solo"
    datadir="/srv/data/azkaban-solo"
    logdir="/var/log/azkaban-solo"

    if ! getent group "$group" > /dev/null 2>&1 ; then
      addgroup --system "$group" --quiet
    fi

    if ! id "$user" > /dev/null 2>&1 ; then
      adduser --system --home "$serverdir" --no-create-home \
        --ingroup "$group" --disabled-password \
        --shell /bin/bash "$user"
    fi

    install -d -o "$user" -g "$group" -m 0755 "$datadir"
    install -d -o "$user" -g "$group" -m 0755 "$logdir"

    chown -R "$user":"$group" /opt/azkaban-solo
    ;;
esac
